name = "backend"
main = "src/index.ts"
compatibility_date = "2024-12-31"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMjEyMDFjY2YtMTJhYi00ZDJmLWEwMDYtYzE2NTViZTQyYWY1IiwidGVuYW50X2lkIjoiMjU4MjYzNTc5MDU1YjRlZmYxMjE3MzFkMjAyNWNhNjU3MzIxYzYwMTk2NWVjYzg4Mjc5ODJlMGY2YjNjMmMxZiIsImludGVybmFsX3NlY3JldCI6IjZkYTFhMjNlLWY5MmEtNDU0Ni1hMTUzLTE2ZjYyYjcwMjAwMSJ9.e9jzPgS3h-qMIDGyeQ1N6qu63PEWVxS6EkTHFoSroMw"
JWT_SECRET = "s3cret"


# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1